# Generated by Django 4.1.2 on 2023-01-19 17:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_avatar_alter_user_email_alter_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='id',
        ),
        migrations.AddField(
            model_name='note',
            name='unique_note_identity',
            field=models.UUIDField(default=uuid.UUID('68a6852c-bf4c-42d7-9007-8ff290635ab7'), primary_key=True, serialize=False),
        ),
    ]
